name: Test

on:
  push:
    branches:
      - dev
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: See storage images
        run: |
          sudo ls -la /var/lib/docker
          sudo ls -la /var/lib/docker/overlay2
          sudo du -sh /var/lib/docker
          sudo du -sh /var/lib/docker/overlay2

      - name: Restore cached docker images
        id: cache-primes-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            /var/lib/docker/overlay2
          key: ${{ runner.os }}-images

      - name: Testing start images
        uses: text-adi/cache-uses-action@dev
        env:
          IMAGE: github/super-linter:slim-v4

      - name: Save Primes
        id: cache-primes-save
        if: always()
        uses: actions/cache/save@v3
        with:
          path: |
            /var/lib/docker/overlay2
          key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}

      - name: See storage images
        if: always()
        run: |
          sudo ls -la /var/lib/docker
          sudo ls -la /var/lib/docker/overlay2
          sudo du -sh /var/lib/docker
          sudo du -sh /var/lib/docker/overlay2
