name: Test

on:
  push:
    branches:
      - dev
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: See storage images
        run: ls -la /var/lib/docker

      - name: Testing start images
        uses: text-adi/cache-uses-action@dev
        env:
          IMAGE: textadi/build-language-i18n-action:v2

      - name: See storage images
        run: ls -la /var/lib/docker